### ISSUE TITLE
ahout install.sh

### ISSUE THREAD

**Issue by 3412596493** [LunacyZeus/Python3.6-for-Centos7.0#1]
兄弟，注释里面清不要写中文。。。

**Comment by gostfather** [comment]
/usr/bin/install: 无法创建普通文件"/usr/local/bin/python3.6m": 权限不够
make: *** [altbininstall] 错误 1

**Comment by gostfather** [comment]
/usr/bin/install: 无法创建普通文件"/usr/local/bin/python3.6m": 权限不够
make: *** [altbininstall] 错误 1

**Comment by LunacyZeus** [comment]
@3412596493 不好意思 我之前写这个就是在腾讯云和阿里云上测试的 直接就能用 没考虑其它的 我等下改下吧 谢谢指出错误!

**Comment by LunacyZeus** [comment]
@gostfather 兄弟 你这个是权限的问题吧
